# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://fsprojects.github.io/FsBlog
gitlocation: https://github.com/fsprojects/FsBlog.git
gitbranch: gh-pages
title: FsBlog
subtitle: Blog aware, static site generation using F#.
description: >
    FsBlog aims to be a blog-aware static site generator, mostly built in F#. But don't worry,
    you won't even need to know any F# to get up and running. So long as you are comfortable
    using a command line or terminal, and have a degree of familiarity with Markdown and Razor
    syntax - you're good to go!

source: ../BlogContent/
blog: ../BlogContent/blog/
blogIndex: ../BlogContent/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: ../Output/
deploy: deploy
themes: themes
